version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      OLLAMA_BASE_URL: http://host.docker.internal:11435
    volumes:
      - open-webui:/app/backend/data
    restart: always
    depends_on:
      ollama:
        condition: service_started
    networks:
      - webnet


  ollama:
    image: ollama/ollama
    container_name: ollama
    hostname: ollama
    environment:
      OLLAMA_HOST: http://0.0.0.0:11435
    ports:
      - "11435:11435"
    networks:
      - webnet
    volumes:
      - ./start_ollama.sh:/usr/local/bin/start_ollama.sh
    entrypoint: ["/bin/bash", "-c", "/usr/local/bin/start_ollama.sh"]

networks:
  webnet:
    driver: bridge

volumes:
  open-webui:
